# Generated by Django 3.1 on 2020-09-03 06:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('yuwen', models.IntegerField()),
                ('shuxue', models.IntegerField()),
                ('yingyue', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
            },
        ),
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AlterModelManagers(
            name='students',
            managers=[
                ('stuObj', django.db.models.manager.Manager()),
            ],
        ),
    ]
